#! /usr/bin/env bash
echo -e "Backup in progress\nUse tail on ~/.logs/rsync.log to monitor progress" | xargs -0 notify-send -i gtk-harddisk
rsync -auP /home/itwenty/Music/ /run/media/itwenty/data/Music/
rsync -auP /home/itwenty/Videos/ /run/media/itwenty/data/Videos/
rsync -auP /home/itwenty/Images/ /run/media/itwenty/data/Images/
rsync -auP /home/itwenty/Unsynced/ /run/media/itwenty/data/Unsynced/
rsync -auP /home/itwenty/OS/ /run/media/itwenty/data/OS/
rsync -auP /home/itwenty/Dropbox/ /run/media/itwenty/data/Dropbox/
if [ $? -ne 0 ]; then
    echo -e "Backup failed!" | xargs -0 notify-send -i important
else
    echo -e "Backup successful" | xargs -0 notify-send -i download
fi
